### ISSUE TITLE
Client hangs with Stack Overflow error in latest.log. 

### ISSUE THREAD

**Issue by Gunner76th** [Electroblob77/Wizardry#299]
Please read the [guide for contributing](https://github.com/Electroblob77/Wizardry/blob/1.12.2/guide_for_contributing.md) before posting.

Minecraft version: 1.12.2 
Wizardry version: ElectroblobsWizardry-4.2.5-MC1.12.2
Environment: Singleplayer

Issue details: [describe what you were doing when the issue occurred, what went wrong, what you expected to happen, etc.]
While individuals are playing in single player, and they go to sleep in a bed, or step through a portal the game "locks up" so to speak and then when they try to close it they have to force close it. In most instances the player inventory is unaffected, however the world is reverted back up to what it was 2 hours prior. Upon investigation it was discovered with a high level of suspicion that Electroblobs Wizardry was to blame due to the following reasons: 

1) The issue only started happening when Electroblobs Wizardry was updated in the modpack to the version listed above, the previous version did not have this issue

2) The issue at hand when research was found to be almost identical to an issue faced back in Jan 4 2018 which was posted here: https://www.minecraftforge.net/forum/topic/62435-minecraft-hangs-doesnt-crash-when-saving/

3) Based on the above referenced bug report having an almost identical error (Stack Overflow) and the fact it was dealing with Wand Data, and the fact that within the modpack Electroblobs Wizardry is the only mod that deals with wands. 

Now, while the log files don't clearly state that Electroblobs Wizardry is causing the issue, based on the evidence at hand (Electroblobs Wizardry recently having been updated, the similarity between this issue and the one from Jan 4 2018, and both issues involving Wand data, and Electroblobs Wizardry being the only mod in the pack that deals with wands) we are fairly certain that Electroblobs Wizardry is the root cause of the problem. We are continuing research into the issue, to include having the affected users revert only Electroblobs Wizardry back to the version that was used in RAD 1.32 to see if the problem persists. We will advise once sufficient testing has been conducted and we have reliable results to report. 

Other mods involved: [only list mods that are relevant to the problem]
https://www.curseforge.com/minecraft/modpacks/roguelike-adventures-and-dungeons
The version with the issue is 1.33. As stated above, version 1.32 does not have the problem, and Electroblobs Wizardry was updated in 1.33. 

Link to crash report (if applicable): [give a link to the crash report on gist, pastebin, etc.]
[latest (4).log](https://github.com/Electroblob77/Wizardry/files/3799090/latest.4.log)
[latest (7).log](https://github.com/Electroblob77/Wizardry/files/3799091/latest.7.log)
[latest (1).log](https://github.com/Electroblob77/Wizardry/files/3799096/latest.1.log)

If you wish to speak with us directly on this issue, you can contact myself or Dreams (the creator of the modpack in question) at the following Discord: https://discord.gg/ZsrYtDb
I am currently the one who is leading the investigation into this issue in an attempt to both find the root cause, as well as a possible solution.

**Comment by Gunner76th** [comment]
***Update***
So from initial testing, reverting from 4.2.5 to 4.1.4 seems to have resolved all issues players were experiencing. It is also confirmed that it was in fact Electroblob Wizardry causing the issue, due to the fact that ALL players having the issue had started working on the Wizardry stuff, and one or two of them even had wands in their possession at the time of the issues. 

At this time I am considering it conclusive that version 4.2.5 is bugged and using it in single player is the definitive cause of the problem.

**Comment by Electroblob77** [comment]
Although the issue you liked on the forge forums was nothing to do with wizardry (I'm guessing you knew that), it does tell me that the problem is an infinite loop in NBT. I don't know where in wizardry's code this happened, so it's going to take a while to get to the bottom of this. To help with this, could you try a few things:

1. Create a fresh world and travel to another dimension with a wand and some wizard armour. It would be useful if you could do this for each dimension, including 'technical' ones (I notice one of your logs involves a tent dimension, for instance)
2. Try reproducing the issue with just wizardry.
3. Launch the modpack with wizardry 4.1.4, do some of the things that are causing the issue (sleep, go through a portal, etc.), then quit, switch to wizardry 4.2.5 and try doing those things again in the same world. I'm wondering if this is a problem with updating old saves, this should help confirm that.

**Comment by Gunner76th** [comment]
Sorry I did not reply sooner, as I was not notified in my email about your reply. I have instructed my dev team to conduct the testing above and report back here with their findings as well as their latest.log files at each step in the process. I have instructed them this is a priority issue, and to please work on it asap. With the US holiday of Thanksgiving approaching I am hoping they can get some data to you before hand, however it might not be until after next week before full data and testing is completed.

**Comment by Electroblob77** [comment]
I've looked into this a bit further and found a way to catch circular NBT references and prevent them from being made. This will fix the issue in that it will stop the game freezing, but as a result the data causing the issue won't be stored. I've made it print a message to the log when this happens because really it shouldn't be trying to store NBT tags inside themselves at all. The message looks like this:

`[Client thread/ERROR] [ebwizardry]: Cannot store tag of type TAG_Compound under key '...' as it would result in a circular reference! Please report this (including your full log) to wizardry's issue tracker.`

Once I've released the fix in the next patch, if you see an error like this in the log could you attach the log here? It should tell me what was actually causing the problem so I can fully fix it. Thanks.

**Comment by Bloodbrowser** [comment]
Hello,

I'm currently runing the R.A.D modpack in 1.36 with Electrolobs Wizardry 4.2.9 and I'm still having the same issue as mentionned above.
[crash-2020-03-06_20.57.25-server.txt](https://github.com/Electroblob77/Wizardry/files/4301216/crash-2020-03-06_20.57.25-server.txt)
Most of the time it happened when I go to sleep or soon after I interacted with a backpack.
Thank you very much for your time

**Comment by Electroblob77** [comment]
That is not the same issue. Please don't revive old issues, especially if they have been fixed, as I do not check them (the only reason I saw this is because I happened to look at this issue for something else). Please post a new issue with the full details of your crash. Thanks.
